### ISSUE TITLE
 I would like to know what version of Python you have, the version of ROS2 installed, and the dependent versions

### ISSUE THREAD

**Issue by Mrkofly** [AndersonYu7/YOLOv7_ROS2#1]
﻿

I would like to know what version of Python you have, the version of ROS2 installed, and the dependent versions

**Comment by AndersonYu7** [comment]
Below are the current versions I am using:

python: 3.10.12
ROS2: Humble

cuda: 11.8

numpy: 1.24.4
opencv-python: 4.9.0.80
torch 2.2.2+cu118
torchaudio: 2.2.2+cu118
torchvision 0.17.2+cu118
tqdm: 4.66.2
pandas: 2.2.2
requests: 2.31.0
seaborn: 0.13.2

**Comment by Mrkofly** [comment]
Okay, thank you for your guidance

**Comment by Mrkofly** [comment]
I think you can add a requirement.txt in the feature pack. Here are some suggestions for you to adopt
